### ISSUE TITLE
Error during server start

### ISSUE THREAD

**Issue by clmc99** [MultiCoreNetwork/carpet-redcraft-addons#195]
After enabling some Redcraft tweaks, Minecraft 1.19 crashes during the "Preparing spawn area" stage of the world starting. Crash report and carpet.conf are attached below. I should note that the error has something to do with the redcraft datapack; the datapack folder itself appears to be empty, containing nothing but a pack.mcmeta file.
```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 8/14/22, 5:22 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResourceAsStream(String)" because the return value of "java.lang.Class.getClassLoader()" is null
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.copyElementFromJar(DatapackUtil.java:246)
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.copyElement(DatapackUtil.java:234)
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.updateRule(DatapackUtil.java:199)
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.registerRule(DatapackUtil.java:189)
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.initializeRules(DatapackUtil.java:147)
	at it.multicoredev.carpetredcraftaddons.util.DatapackUtil.initializeDatapack(DatapackUtil.java:133)
	at it.multicoredev.carpetredcraftaddons.CarpetRedCraftExtension.onServerLoadedWorlds(CarpetRedCraftExtension.java:52)
	at carpet.CarpetServer.lambda$onServerLoadedWorlds$3(CarpetServer.java:108)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:108)
	at net.minecraft.server.MinecraftServer.handler$bhg000$serverLoadedWorlds(MinecraftServer.java:5787)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:331)
	at net.minecraft.class_3176.method_3823(class_3176.java:172)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:637)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 3.10.0-1160.53.1.el7.x86_64
	Java Version: 17.0.3, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
	Memory: 2115360112 bytes (2017 MiB) / 3875536896 bytes (3696 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 3900X 12-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 68478.26
	Virtual memory used (MB): 71569.07
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 3882.19
	JVM Flags: 19 total; -Xms1G -Xmx12G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		adorn: Adorn 3.6.1+1.19
		advdebug: Advancements Debug 2.3.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.10.33
		artifacts: Artifacts 7.1.1+fabric
			com_github_llamalad7_mixinextras: MixinExtras 0.0.11
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 15.0.2
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.8
		axesareweapons: Axes Are Weapons 1.6.0
		badpackets: Bad Packets 0.1.2
		bclib: BCLib 2.0.17
		betteranimalsplus: Better Animals Plus 1.19-11.0.7
		betterdeserttemples: YUNG's Better Desert Temples 1.19-Fabric-2.0
		betterend: Better End 2.0.10
		bettermineshafts: YUNG's Better Mineshafts 1.19-Fabric-3.0
		betternether: Better Nether 7.0.7
		bettersafebed: BetterSafeBed 4
		betterspawnercontrol-fabric: Better Spawner Control (Fabric) 1.7
		bigbeacons: Big Beacons 1.2.6
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bowinfinityfix: Bow Infinity Fix 2.5.0
		byg: Oh The Biomes You'll Go 2.0.0.7
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.8.33
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.8.33
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.8.33
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.8.33
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.8.33
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.8.33
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.8.33
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.8.33
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.8.33
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.8.33
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.8.33
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.8.33
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.8.33
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.8.33
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.8.33
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.8.33
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.33
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.8.33
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.8.33
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.33
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carpet: Carpet Mod 1.4.79
		carpet-extra: Carpet Extra 1.4.79
		carpet-fixes: Carpet Fixes 1.19-1.11.2
			conditional-mixin: conditional mixin 0.3.0
		carpet-redcraft-addons: Carpet RedCraft Addons 1.4.79
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cloth-config: Cloth Config v6 7.0.73
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		conduitspreventdrowned-fabric: Conduits Prevent Drowned (Fabric) 1.6
		conjuring: Conjuring 1.0.24+1.19
		croptopia: Croptopia 2.0.7
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		ctov: ChoiceTheorem's Overhauled Villages 3.0.1
		dcch: DCCH 1.2
		deepslatecutting: Deepslate Cutting 1.4.0
			maybe-data: Maybe data 1.3.1-1.18.2
		deepslateinstamine: Deepslate Instamine 1.5.1
		difficultytweaker: Difficulty Tweaker 0.3.0+1.19
		dismountentity-fabric: Dismount Entity (Fabric) 1.7
		dropspread: Drop Spread 1.3.0
		dual_riders: Dual Riders 1.1.2
		dungeons_arise: When Dungeons Arise 2.1.51
		easyautocrafting: EasyAutoCrafting 1.5+1.19
		enchantablehorsearmor: Enchantable Horse Armor 1.0a
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.4
		experiencebugfix: Experience Bug Fix 18
		extractpoison-fabric: Extract Poison (Fabric) 1.8
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		ferritecore: FerriteCore 4.2.1
		fishonaleash: Fish on a Leash! 1.18.1-1.0.0
		flytre_lib: FlytreLib 1.8.8
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		glow: Actually Glow Berries 1.0.3
		handoveryouritems-fabric: Hand Over Your Items (Fabric) 1.5
		infinitevillagertrading: InfiniteVillagerTrading 1.19-fabric0.53.3-1.1
		infinitywaterbucket: Infinity Water Bucket 2.0.0
		java: OpenJDK 64-Bit Server VM 17
		kibe: Kibe 1.9.9-BETA+1.19
			playerabilitylib: Pal 1.6.0
		lazydfu: LazyDFU 0.1.3
		leaf-decay: Leaf Decay 1.4.0-1.19
		libraryferret: Library Ferret 2.0.0
		lithium: Lithium 0.8.3
		mcwbridges: Macaw's Bridges 2.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwroofs: Macaw's Roofs 2.1.2
		megane: megane 8.2.0
			megane-api: megane-api 8.2.0
			megane-fabric-transfer: megane-fabric-transfer 8.2.0
			megane-kibe: megane-kibe 8.2.0
			megane-runtime: megane-runtime 8.2.0
			megane-vanilla: megane-vanilla 8.2.0
		memoryleakfix: memory Leak Fix 1.19-0.5.4
		milkallthemobs-fabric: Milk All The Mobs (Fabric) 1.8
		minecraft: Minecraft 1.19
		minitweaks: MiniTweaks 1.19-1.3.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		nbtcrafting: NBT Crafting 2.1.4+mc1.19
		owo: oωo 0.7.3+1.19
		patchouli: Patchouli 1.19-74-FABRIC
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.45.0+1.19.1
		pvptoggle: Pvp Toggle 1.0.6
		rainbegoneritual-fabric: Rain Be Gone Ritual (Fabric) 1.9
		recipecache: recipecache 0.2.0-1.19
		repurposed_structures: Repurposed Structures 6.1.1+1.19
			midnightlib: MidnightLib 0.5.2
		reputation: Your Reputation 0.1.3+1.19
		roughlyenoughitems: Roughly Enough Items 9.1.524
		servux: Servux 0.1.0
		slipperywalls: SlipperyWalls 1.0.0+1.17
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8
		tabtps-fabric: TabTPS 1.3.14
			adventure-platform-fabric: adventure-platform-fabric 5.4.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.11.0
				net_kyori_adventure-key: adventure-key 4.11.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.1.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.11.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.11.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.11.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.11.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-core_: cloud-core 1.8.0-SNAPSHOT
				cloud_commandframework_cloud-services_: cloud-services 1.8.0-SNAPSHOT
				io_leangen_geantyref_geantyref: geantyref 1.3.13
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.0-SNAPSHOT
			com_typesafe_config: config 1.4.2
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.11.0
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.11.0
		terrablender: TerraBlender 2.0.0.120
		trinkets: Trinkets 3.4.0
		vanish: vanish 1.4.1
		vmp: Very Many Players 0.2.0+beta.6.0
		voidtotem: Void Totem 2.0.0
		wither_cage_fix: Wither Cage Fix 1.0.13
		worldedit: WorldEdit 7.2.11-beta-01+6200-0877589
		wthit: wthit 5.8.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		yungsapi: YUNG's API 1.19-Fabric-3.4.1
		yungsbridges: YUNG's Bridges 1.19-Fabric-3.0
	Server Running: true
	Player Count: 0 / 20; []
	Data Packs: vanilla, file/cheemspuff_bartering.zip, file/cheemspuff_end portal frames.zip, file/cheemspuff_jungle saplings.zip, file/cheemspuff_warped forest.zip, file/cheemspuff_lush caves fix.zip, Fabric Mods, file/AllMobHeads_V7.2 MODIFIED.zip, file/Astronaut Piglins Ver 0.1 - 1.16 Devon Datapack MODIFIED.zip, file/Fancier+Mansions+v1.0 MODIFIED.zip, file/Repurposed_Structures-Config_Datapack-1_19_0-v19 MODIFIED.zip, file/Statue.zip, file/alcohol-v1 MODIFIED.zip, file/ancient-cities-overhaul-nikeyso.zip, file/anti enderman grief v1.1.3.zip, file/anti ghast grief v1.1.3.zip, file/armor statues v2.8.4.zip, file/armored elytra v1.0.6 MODIFIED.zip, file/cauldron concrete v2.0.6.zip, file/chunk loaders v1.0.4.zip, file/derecchorusflowerdrops MODIFIED.zip, file/elevators v1.0.4.zip, file/infestedblockdrops.zip, file/more-trapdoors-e3300 MODIFIED.zip, file/silence mobs v1.1.3.zip, file/tag v2.1.3.zip, file/terralith-v2-3-2a.zip, file/unlock all recipes v2.0.4.zip, file/wandering trades v1.6.0.zip, file/allay-duplication.zip, file/ichphilipp-s-endcity-better-end-1-18-1 MODIFIED.zip, file/cheemspuff_crafting recipes.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```
[carpet.conf.txt](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/9334228/carpet.conf.txt)

**Comment by edgvrl** [comment]
have almost the same issue 
[crash-2022-10-05_06.15.29-server.txt](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/9713779/crash-2022-10-05_06.15.29-server.txt)

heres my carpet.conf
[carpet.conf.txt](https://github.com/MultiCoreNetwork/carpet-redcraft-addons/files/9713790/carpet.conf.txt)

**Comment by Pietr06** [comment]
Btw I really recommend to not use this mod anymore, since all the features are now implemented as scripts and can be easily downloaded via /script download and no one is working anymore on this mod

**Comment by edgvrl** [comment]
oh okay then thank you

**Comment by clmc99** [comment]
> Btw I really recommend to not use this mod anymore, since all the features are now implemented as scripts and can be easily downloaded via /script download and no one is working anymore on this mod

where would I find these features to download?

**Comment by ghost** [comment]
Hello @Pi3tro88, like @clmc99, I would love to know where I can find them.

I was looking at the scripts from carpet but there I can't find the exact rules.
I would love to use **placeablePlants** and **dynamicLight** again ❤️

**Comment by Pietr06** [comment]
> Hello @Pi3tro88, like @clmc99, I would love to know where I can find them.
> 
> I was looking at the scripts from carpet but there I can't find the exact rules.
> I would love to use **placeablePlants** and **dynamicLight** again ❤️

Oh sorry didn't saw the notification @clmc99 btw you can find most of the scripts here https://github.com/gnembon/scarpet/tree/master/programs, but some of the ones made by bisumto are only here https://github.com/BisUmTo/scarpet, to install them do 
/carpet setDefault scriptsAppStore bisumto/scarpet/contents

/script download ...

Or directly download the file from the page and put it into the script folder into the world folder

**Comment by ghost** [comment]
Thank you so, so, so much!!
It's my first time that I am looking into the script section of the carpet extension.
Awesome!
